version: '2'
services:
  eth:
    privileged: true
    build: monitored-geth-client
    restart: on-failure
    container_name: eth    
    links:
      - netstats
    entrypoint: /root/start.sh
    command: '--syncmode "fast" --cache=512 --rpc --rpccorsdomain="*" --rpcapi "eth,web3" --rpcaddr="0.0.0.0"'
    volumes:
      # - /etc/localtime:/etc/localtime:ro
      - ./src:/src:ro
      - ./.ethereum:/root/.ethereum:rw
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
      - "30303:30303/udp"
      - "30304:30304/udp"
  netstats:
    build: eth-netstats
    restart: on-failure
    container_name: netstats
    environment:
      - WS_SECRET=eth-net-stats-secret
    #volumes:
    #  - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
